export declare const dataMap: {
    let: string;
    const: string;
    return: string;
    continue: string;
    break: string;
    if: string;
    else: string;
    switch: string;
    case: string;
    default: string;
    while: string;
    for: string;
    of: string;
    do: string;
    import: string;
    from: string;
    require: string;
    function: string;
    typeof: string;
    Promise: string;
    async: string;
    await: string;
    'console.log': string;
};
